name: Result mode reusable finalizer

on:
  workflow_call:
    inputs:
      context:
        type: string
        required: true
      job_results:
        type: string
        required: true

permissions: {}

jobs:
  result:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write
      pull-requests: write
    steps:
      - uses: GrantBirki/branch-deploy@5bbc408085344b9f71ca9ae9d66b7669d97897e7
        if: ${{ always() }}
        with:
          result_mode: true
          context: ${{ inputs.context }}
          job_results: ${{ inputs.job_results }}
          result_url: https://example.com/branch-deploy-acceptance
